# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField(blank=True)),
                ('check_out_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Item')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Patron')),
            ],
        ),
    ]
