# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-29 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
