# Generated by Django 2.0.5 on 2018-05-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170728_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='catalog_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
