# Generated by Django 2.0.5 on 2018-05-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180511_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('book', (('author', 'Author'), ('illustrator', 'Illustrator'), ('introduction', 'Introduction'), ('translator', 'Translator'))), ('film', (('director', 'Director'), ('writer', 'Writer'), ('editor', 'Editor'), ('composer', 'Composer'))), ('music', (('artist', 'Artist'),))], default='author', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_type',
        ),
        migrations.AlterField(
            model_name='item',
            name='authors',
            field=models.ManyToManyField(blank=True, to='catalog.Authorship'),
        ),
        migrations.AddField(
            model_name='authorship',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Author'),
        ),
    ]
