# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170627_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='authors',
            field=models.ManyToManyField(blank=True, to='catalog.Author'),
        ),
    ]
