# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170627_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_type',
            field=models.CharField(choices=[('book', (('author', 'Author'), ('illustrator', 'Illustrator'), ('introduction', 'Introduction'), ('translator', 'Translator'))), ('film', (('director', 'Director'), ('writer', 'Writer'), ('editor', 'Editor'), ('composer', 'Composer'))), ('music', (('artist', 'Artist'),))], default='writer', max_length=50),
        ),
    ]
