# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170628_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_type',
            field=models.CharField(choices=[('book', (('author', 'Author'), ('illustrator', 'Illustrator'), ('introduction', 'Introduction'), ('translator', 'Translator'))), ('film', (('director', 'Director'), ('writer', 'Writer'), ('editor', 'Editor'), ('composer', 'Composer'))), ('music', (('artist', 'Artist'),))], default='author', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='media_type',
            field=models.CharField(choices=[('book', (('hardcover', 'Hardcover'), ('paperback', 'Paperback'), ('magazine', 'Magazine'), ('zine', 'Zine'))), ('film', (('dvd', 'DVD'), ('bluray', 'Blu-Ray'), ('vhs', 'VHS'), ('laserdisc', 'Laserdisc'))), ('music', (('record', 'Vinyl Record'), ('cd', 'CD'), ('cdr', 'CD-R'), ('cassette', 'Cassette Tape'), ('usb', 'USB Drive')))], max_length=50),
        ),
    ]
