# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170628_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='upc',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
